### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [carrafa/dungeon-land#1]
I am incredibly impressed with what you built here. Not only does the output look great but your code is very cleanly written and commented, and you seperated your files to make it easier to understand what does what. 

 I still haven't gotten past the second dragon level as the wizard, he hit me with a fireball :frowning: . What did you use to teach yourself canvas? What did you see as the biggest challenge working with canvas? 

Overall keep up the great work!

**Comment by ajhofferber** [comment]
Hey Josh,

Cool game! I second Avi in that I am really impressed with what you were able to create.  Also, props for diving into canvas and trying out something new. It seems like you had some fun with it!  Your code is organized very logically and the commenting out really helps us understand what each part of your code is responsible for.

Did you ever end up messing more with the fog feature? That would be rad to see if you could figure that out someday. It was cool to see your process on this as you went, and I think you should be really proud of your final project! Plus it's super fun to play and I am really bad at it but that is okay. 

Score: 3 (refer to project markdown for scoring rubric)

-Ash

**Comment by carrafa** [comment]
Thanks guys! Ben and I actually discovered canvas together the day the project was announced, and we were sending random canvas games tutorials back and forth that weekend.  Those tutorials combined with the Canvas API on mdn are basically all I used.  

For me, the biggest leap was getting the idea that it really is just a _canvas_.  Once you paint something on there, that's it.  It's not like html where you can manipulate something that already exists.  If you want to move it, you have to erase it and draw it again in a different place.  Once I got a good handle of that everything started to make more sense.  The getImageData was also a huge pain because I was doing it the wrong way for a long time, but the way I have it now works ok.

I ended up getting a fog thing to kind of work.  It would create a visible area around the guy but it wouldn't leave the areas explored visible.  But yeah, I would like to get that functional as well.  

And a bigger stretch idea for this game is to have a level and character creator for a user.  So I'd have a little pixel drawing tab where the user could draw a map and characters and basically have user created levels.  I may have to simplify the art, but if I give someone a 500x500 black square and a red pixel drawing tool they could draw any level.  Then the character drawing tab would have a 30x30 square and the user could draw whatever and set it as a hero or an enemy, then tell it where to put it on the map.  There would be some nuances like obstacles and staircases, but I think it's doable.  Then users could upload their own worlds and there could be a database of user created games.

anyway, thanks!
